name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links with Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --accept 200,204,429
            --retry-wait-time 2
            --max-retries 3
            .
